// Generated by CoffeeScript 1.8.0
(function() {
  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    var base_url;
    base_url = "http://nodejs-questionsapi.rhcloud.com/youtube-api";
    switch (request.type) {
      case 'youtube-comments':
        console.log('b');
        $.getJSON("" + base_url + "/youtube_comments?id=" + request.id, (function(_this) {
          return function(data) {
            return sendResponse(data);
          };
        })(this));
        break;
      case 'youtube-stats':
        console.log('a');
        $.getJSON("" + base_url + "/youtube_stats?id=" + request.id, (function(_this) {
          return function(data) {
            return sendResponse(data);
          };
        })(this));
    }
    return true;
  });

}).call(this);
