// Generated by CoffeeScript 1.8.0
(function() {
  var a, coffeescript, current_time, div, duration, h1, h3, iframe, img, input, link, locInterval, p, raw, script, span, teacup, timeToSeconds;

  teacup = window.window.teacup;

  span = teacup.span, div = teacup.div, a = teacup.a, h1 = teacup.h1, h3 = teacup.h3, p = teacup.p, iframe = teacup.iframe, raw = teacup.raw, script = teacup.script, coffeescript = teacup.coffeescript, link = teacup.link, input = teacup.input, img = teacup.img;

  locInterval = function(time, next) {
    return setInterval(next, time * 1000);
  };

  timeToSeconds = function(time) {
    var elements, seconds;
    seconds = 0;
    elements = time.split(':').reverse();
    if (elements[0]) {
      seconds += parseInt(elements[0]);
    }
    if (elements[1]) {
      seconds += parseInt(elements[1]) * 60;
    }
    if (elements[2]) {
      seconds += parseInt(elements[2]) * 60 * 60;
    }
    if (elements[3]) {
      seconds += parseInt(elements[3]) * 24 * 60 * 60;
    }
    return seconds;
  };

  current_time = $('#movie_player > div.html5-video-controls > div.html5-player-chrome > span > div.ytp-time-display.html5-control > span.ytp-time-current');

  duration = $('#movie_player > div.html5-video-controls > div.html5-player-chrome > span > div.ytp-time-display.html5-control > span.ytp-time-duration');

  locInterval(1, function() {
    var current_seconds;
    if (!$("#content").length) {
      return;
    }
    console.log($("#content #overlay-wrapper"), 'wtf');
    if (!$("#content #overlay-wrapper").length) {
      console.log("INITIALIZED");
      return $("#content").prepend(teacup.render(((function(_this) {
        return function() {
          return div('#overlay-wrapper', function() {
            div('.images');
            return div('.comment', function() {
              img({
                src: 'https://gp3.googleusercontent.com/-pmGKuLJC7qU/AAAAAAAAAAI/AAAAAAAAABg/aItmNTS9xEY/s48-c-k-no/photo.jpg'
              });
              return span(function() {
                return 'The stuff he starts playing at 9:47 and onwards. Could someone please give me some advice to learning this style? books?﻿';
              });
            });
          });
        };
      })(this))));
    } else {
      console.log('BEFORE', current_time.text());
      current_seconds = timeToSeconds(current_time.text());
      return console.log($('a[rel="nofollow"]'));
    }
  });

}).call(this);
