// Generated by CoffeeScript 1.8.0
(function() {
  var timeToSeconds;

  timeToSeconds = function(time) {
    var elements, seconds;
    if (time == null) {
      time = "02:58 xDDD﻿";
    }
    seconds = 0;
    elements = time.split(':').reverse();
    if (elements[0]) {
      seconds += parseInt(elements[0]);
    }
    if (elements[1]) {
      seconds += parseInt(elements[1]) * 60;
    }
    if (elements[2]) {
      seconds += parseInt(elements[2]) * 60 * 60;
    }
    if (elements[3]) {
      seconds += parseInt(elements[3]) * 24 * 60 * 60;
    }
    return seconds;
  };

  console.log(timeToSeconds());

}).call(this);
