// Generated by CoffeeScript 1.8.0
(function() {
  var getComments;

  require('./async.min.js');

  require('./jquery.min.js');

  getComments = (function(_this) {
    return function(num) {
      var calls, count, start_index, video_id;
      if (num == null) {
        num = 368;
      }
      calls = [];
      count = 0;
      video_id = 'AJDUHq2mJx0';
      while (num > 0) {
        start_index = (count * 50) + 1;
        calls[count] = "https://gdata.youtube.com/feeds/api/videos/AJDUHq2mJx0/comments?start-index=" + start_index + "&max-results=50";
        num -= 50;
        count++;
        break;
      }
      return async.map(calls, (function(call, done) {
        console.log(call, '213');
        return $.ajax({
          url: call,
          dataType: "xml",
          success: (function(_this) {
            return function(data) {
              return $(data).find('entry').each(function(index, el) {
                var $el;
                $el = $(el);
                return data = {
                  data_url: "http://gdata.youtube.com/feeds/api/users/" + ($el.find('yt:channelId').text()) + "?fields=yt:username,media:thumbnail,title",
                  comment: $el.find('content[type="text"]').text()
                };
              });
            };
          })(this)
        });
      }), function(err, finish) {
        return console.log(finish, '123');
      });
    };
  })(this);

  getComments();

}).call(this);
